#!/usr/bin/env python

import subprocess
import time
import argparse

# -----
# Parser

parser = argparse.ArgumentParser()
    
parser.add_argument('action')

args = parser.parse_args()

# -----
# Config

supported_actions = ['low', 'high']

# -----
# Main

action = args.action

if not (action in supported_actions):
    print("Unsupported action. Supported actions are:")
    print(supported_actions)
    sys.exit(1)

script = open('script.sh', 'w')
script.write('#!/bin/bash\n')
script.write('echo "{}" > /sys/class/drm/card0/device/power_dpm_force_performance_level\n'.format(action))
script.close()

subprocess.call('chmod +x script.sh', shell=True)

while True:
    print('Setting frequencies...')
    subprocess.call('./script.sh', shell=True)
    time.sleep(10)
