#!/usr/bin/env python

import subprocess
import time

while True:
    cmd = 'echo low > /sys/class/drm/card0/device/power_dpm_force_performance_lev'
    subprocess.call(cmd, shell=True)
    time.sleep(10)
